codecov:
    require_ci_to_pass: yes

coverage:
    precision: 2
    round: down
    range: "70...100"
    status:
        patch: true
    parsers:
        gcov:
            branch_detection:
                conditional: yes
                loop: yes
                method: no
                macro: no
ci:
    yml:
comment:
    layout: "diff,flags,files,footer"
    behavior: default
    require_changes: no

github_checks:
    annotations: true
